storage: use AtomicBool for is_dirty flag
Switch from bool to atomicbool type for the storage's is_dirty flag.
This change is primariry for thread safety since the flag is accessed
and can be changed by different threads.

error: implement a more convenient method for getting the error's inner
type message field.

doc: Provide more code documentation